### PR TITLE
codebase changed issue solved.

### LINKED ISSUE #4: Codebase Has Changed.
### As Codebase Has Changed, All The Existing Code must be replaced with a new code written in C++. Do it as soon as possible.

### PR DESCRIPTION
**Pull request by acousticclown**
I have Changed the Codebase from normal _batch files_ and _python_ files to **Electron JS Application Codebase**. Please review my code.

#### What has Changed

1. Python Dependencies removed.
2. batch files removed.
3. Electron JS Template Added for further working.
4. Additional folder named **OF** is included containing Older Codebase for No Confusion. May be deleted Later. #4 #4

### CODE REVIEW

**Comment by Mohit-Vishwakarma** [comment]
Thank you Shivansh for your contribution @acousticclown

**Comment by Mohit-Vishwakarma** [comment]
Thank you @acousticclown  for your Contribution.

**Comment by Mohit-Vishwakarma** [comment]
Thank you @acousticclown for your Contribution.
Your Pull request has been merged.

**Comment by acousticclown** [comment]
@Mohit-Vishwakarma Thank You For Merging.

**Pull request merged**
